### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ducpro0211kk** [MehulKhanna/PokeGrinder#3]
Traceback (most recent call last):
  File "C:\Users\ADMIN\Downloads\PokeGrinder-master\PokeGrinder-master\main.py", line 9, in <module>
    client = commands.Bot(command_prefix="$")
TypeError: BotBase.__init__() missing 1 required keyword-only argument: 'intents'

**Comment by MehulKhanna** [comment]
> C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\bot.py:618: RuntimeWarning: coroutine 'setup' was never awaited setup(self) RuntimeWarning: Enable tracemalloc to get the object allocation traceback Traceback (most recent call last): File "C:\Users\ADMIN\Downloads\PokeGrinder-master\PokeGrinder-master\main.py", line 18, in asyncio.run(load_cogs()) File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "C:\Users\ADMIN\Downloads\PokeGrinder-master\PokeGrinder-master\main.py", line 14, in load_cogs await client.load_extension("cogs.startup") TypeError: object NoneType can't be used in 'await' expression

This was an issue with the requirements.txt file, I will update the installations steps. I will also soon be uploading an executable which you can run if you encounter installation issues.

**Comment by MehulKhanna** [comment]
> C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\bot.py:618: RuntimeWarning: coroutine 'setup' was never awaited setup(self) RuntimeWarning: Enable tracemalloc to get the object allocation traceback Traceback (most recent call last): File "C:\Users\ADMIN\Downloads\PokeGrinder-master\PokeGrinder-master\main.py", line 18, in asyncio.run(load_cogs()) File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "C:\Users\ADMIN\Downloads\PokeGrinder-master\PokeGrinder-master\main.py", line 14, in load_cogs await client.load_extension("cogs.startup") TypeError: object NoneType can't be used in 'await' expression

This error has been fixed, please try to install using the executable that has now been provided and installation instructions for which are provided in the readme.

**Comment by ducpro0211kk** [comment]
> > C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\bot.py:618: RuntimeWarning: coroutine 'setup' was never awaited setup(self) RuntimeWarning: Enable tracemalloc to get the object allocation traceback Traceback (most recent call last): File "C:\Users\ADMIN\Downloads\PokeGrinder-master\PokeGrinder-master\main.py", line 18, in asyncio.run(load_cogs()) File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "C:\Users\ADMIN\Downloads\PokeGrinder-master\PokeGrinder-master\main.py", line 14, in load_cogs await client.load_extension("cogs.startup") TypeError: object NoneType can't be used in 'await' expression
> 
> This error has been fixed, please try to install using the executable that has now been provided and installation instructions for which are provided in the readme.

Traceback (most recent call last):
  File "C:\Users\ADMIN\Downloads\PokeGrinder-master (1)\PokeGrinder-master\main.py", line 20, in <module>
    client.run(client.token)
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 742, in run
    asyncio.run(runner())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 739, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 712, in start
    await self.login(token)
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 583, in login
    data = await state.http.static_login(token.strip())
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\http.py", line 660, in static_login
    await self.startup()
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\http.py", line 378, in startup
    self.user_agent, self.browser_version, self.client_build_number = ua, bv, bn = await utils._get_info(session)
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\utils.py", line 1246, in _get_info
    bn = await _get_build_number(session)
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\utils.py", line 1255, in _get_build_number
    login_page = await login_page_request.text()
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\aiohttp\client_reqrep.py", line 1076, in text
    await self.read()
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\aiohttp\client_reqrep.py", line 1032, in read
    self._body = await self.content.read()
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\aiohttp\streams.py", line 344, in read
    raise self._exception
aiohttp.client_exceptions.ClientPayloadError: 400, message='Can not decode content-encoding: br'


new error :(

**Comment by MehulKhanna** [comment]
> > > C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\bot.py:618: RuntimeWarning: coroutine 'setup' was never awaited setup(self) RuntimeWarning: Enable tracemalloc to get the object allocation traceback Traceback (most recent call last): File "C:\Users\ADMIN\Downloads\PokeGrinder-master\PokeGrinder-master\main.py", line 18, in asyncio.run(load_cogs()) File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "C:\Users\ADMIN\Downloads\PokeGrinder-master\PokeGrinder-master\main.py", line 14, in load_cogs await client.load_extension("cogs.startup") TypeError: object NoneType can't be used in 'await' expression
> > 
> > 
> > This error has been fixed, please try to install using the executable that has now been provided and installation instructions for which are provided in the readme.
> 
> Traceback (most recent call last): File "C:\Users\ADMIN\Downloads\PokeGrinder-master (1)\PokeGrinder-master\main.py", line 20, in client.run(client.token) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 742, in run asyncio.run(runner()) File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 739, in runner await self.start(*args, **kwargs) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 712, in start await self.login(token) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 583, in login data = await state.http.static_login(token.strip()) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\http.py", line 660, in static_login await self.startup() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\http.py", line 378, in startup self.user_agent, self.browser_version, self.client_build_number = ua, bv, bn = await utils._get_info(session) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\utils.py", line 1246, in _get_info bn = await _get_build_number(session) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\utils.py", line 1255, in _get_build_number login_page = await login_page_request.text() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\aiohttp\client_reqrep.py", line 1076, in text await self.read() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\aiohttp\client_reqrep.py", line 1032, in read self._body = await self.content.read() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\aiohttp\streams.py", line 344, in read raise self._exception aiohttp.client_exceptions.ClientPayloadError: 400, message='Can not decode content-encoding: br'
> 
> new error :(

https://github.com/MehulKhanna/PokeGrinder/releases/download/Full-Release/PokeGrinderExecutable.zip please try to use the executable given in this file

**Comment by ducpro0211kk** [comment]
> > > > C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\bot.py:618: RuntimeWarning: coroutine 'setup' was never awaited setup(self) RuntimeWarning: Enable tracemalloc to get the object allocation traceback Traceback (most recent call last): File "C:\Users\ADMIN\Downloads\PokeGrinder-master\PokeGrinder-master\main.py", line 18, in asyncio.run(load_cogs()) File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "C:\Users\ADMIN\Downloads\PokeGrinder-master\PokeGrinder-master\main.py", line 14, in load_cogs await client.load_extension("cogs.startup") TypeError: object NoneType can't be used in 'await' expression
> > > 
> > > 
> > > This error has been fixed, please try to install using the executable that has now been provided and installation instructions for which are provided in the readme.
> > 
> > 
> > Traceback (most recent call last): File "C:\Users\ADMIN\Downloads\PokeGrinder-master (1)\PokeGrinder-master\main.py", line 20, in client.run(client.token) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 742, in run asyncio.run(runner()) File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 739, in runner await self.start(*args, **kwargs) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 712, in start await self.login(token) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 583, in login data = await state.http.static_login(token.strip()) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\http.py", line 660, in static_login await self.startup() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\http.py", line 378, in startup self.user_agent, self.browser_version, self.client_build_number = ua, bv, bn = await utils._get_info(session) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\utils.py", line 1246, in _get_info bn = await _get_build_number(session) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\utils.py", line 1255, in _get_build_number login_page = await login_page_request.text() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\aiohttp\client_reqrep.py", line 1076, in text await self.read() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\aiohttp\client_reqrep.py", line 1032, in read self._body = await self.content.read() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\aiohttp\streams.py", line 344, in read raise self._exception aiohttp.client_exceptions.ClientPayloadError: 400, message='Can not decode content-encoding: br'
> > new error :(
> 
> https://github.com/MehulKhanna/PokeGrinder/releases/download/Full-Release/PokeGrinderExecutable.zip please try to use the executable given in this file

This version works fine, but when the captcha appears, there is an error
| Time Elapsed: 0:00:02 | Encounters: 1 | Catches: 1
| Time Elapsed: 0:00:14 | Encounters: 2 | Catches: 2
Task exception was never retrieved
future: <Task finished name='Task-25' coro=<timer() done, defined at C:\Users\ADMIN\Downloads\PokeGrinderExecutable\cogs\hunting.py:19> exception=TimeoutError()>
Traceback (most recent call last):
  File "asyncio\tasks.py", line 456, in wait_for
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ADMIN\Downloads\PokeGrinderExecutable\cogs\hunting.py", line 21, in timer
    await command()
  File "discord\commands.py", line 615, in __call__
  File "discord\commands.py", line 261, in __call__
  File "discord\commands.py", line 128, in __call__
  File "asyncio\tasks.py", line 458, in wait_for
asyncio.exceptions.TimeoutError

**Comment by MehulKhanna** [comment]
> > > > > C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\bot.py:618: RuntimeWarning: coroutine 'setup' was never awaited setup(self) RuntimeWarning: Enable tracemalloc to get the object allocation traceback Traceback (most recent call last): File "C:\Users\ADMIN\Downloads\PokeGrinder-master\PokeGrinder-master\main.py", line 18, in asyncio.run(load_cogs()) File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "C:\Users\ADMIN\Downloads\PokeGrinder-master\PokeGrinder-master\main.py", line 14, in load_cogs await client.load_extension("cogs.startup") TypeError: object NoneType can't be used in 'await' expression
> > > > 
> > > > 
> > > > This error has been fixed, please try to install using the executable that has now been provided and installation instructions for which are provided in the readme.
> > > 
> > > 
> > > Traceback (most recent call last): File "C:\Users\ADMIN\Downloads\PokeGrinder-master (1)\PokeGrinder-master\main.py", line 20, in client.run(client.token) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 742, in run asyncio.run(runner()) File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 739, in runner await self.start(*args, **kwargs) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 712, in start await self.login(token) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 583, in login data = await state.http.static_login(token.strip()) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\http.py", line 660, in static_login await self.startup() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\http.py", line 378, in startup self.user_agent, self.browser_version, self.client_build_number = ua, bv, bn = await utils._get_info(session) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\utils.py", line 1246, in _get_info bn = await _get_build_number(session) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\utils.py", line 1255, in _get_build_number login_page = await login_page_request.text() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\aiohttp\client_reqrep.py", line 1076, in text await self.read() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\aiohttp\client_reqrep.py", line 1032, in read self._body = await self.content.read() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\aiohttp\streams.py", line 344, in read raise self._exception aiohttp.client_exceptions.ClientPayloadError: 400, message='Can not decode content-encoding: br'
> > > new error :(
> > 
> > 
> > https://github.com/MehulKhanna/PokeGrinder/releases/download/Full-Release/PokeGrinderExecutable.zip please try to use the executable given in this file
> 
> This version works fine, but when the captcha appears, there is an error | Time Elapsed: 0:00:02 | Encounters: 1 | Catches: 1 | Time Elapsed: 0:00:14 | Encounters: 2 | Catches: 2 Task exception was never retrieved future: <Task finished name='Task-25' coro=<timer() done, defined at C:\Users\ADMIN\Downloads\PokeGrinderExecutable\cogs\hunting.py:19> exception=TimeoutError()> Traceback (most recent call last): File "asyncio\tasks.py", line 456, in wait_for asyncio.exceptions.CancelledError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "C:\Users\ADMIN\Downloads\PokeGrinderExecutable\cogs\hunting.py", line 21, in timer await command() File "discord\commands.py", line 615, in **call** File "discord\commands.py", line 261, in **call** File "discord\commands.py", line 128, in **call** File "asyncio\tasks.py", line 458, in wait_for asyncio.exceptions.TimeoutError

Can you please check and see if this happens with every captcha you encounter?

**Comment by ducpro0211kk** [comment]
> > > > > > C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\bot.py:618: RuntimeWarning: coroutine 'setup' was never awaited setup(self) RuntimeWarning: Enable tracemalloc to get the object allocation traceback Traceback (most recent call last): File "C:\Users\ADMIN\Downloads\PokeGrinder-master\PokeGrinder-master\main.py", line 18, in asyncio.run(load_cogs()) File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "C:\Users\ADMIN\Downloads\PokeGrinder-master\PokeGrinder-master\main.py", line 14, in load_cogs await client.load_extension("cogs.startup") TypeError: object NoneType can't be used in 'await' expression
> > > > > 
> > > > > 
> > > > > This error has been fixed, please try to install using the executable that has now been provided and installation instructions for which are provided in the readme.
> > > > 
> > > > 
> > > > Traceback (most recent call last): File "C:\Users\ADMIN\Downloads\PokeGrinder-master (1)\PokeGrinder-master\main.py", line 20, in client.run(client.token) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 742, in run asyncio.run(runner()) File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 739, in runner await self.start(*args, **kwargs) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 712, in start await self.login(token) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 583, in login data = await state.http.static_login(token.strip()) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\http.py", line 660, in static_login await self.startup() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\http.py", line 378, in startup self.user_agent, self.browser_version, self.client_build_number = ua, bv, bn = await utils._get_info(session) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\utils.py", line 1246, in _get_info bn = await _get_build_number(session) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\utils.py", line 1255, in _get_build_number login_page = await login_page_request.text() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\aiohttp\client_reqrep.py", line 1076, in text await self.read() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\aiohttp\client_reqrep.py", line 1032, in read self._body = await self.content.read() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\aiohttp\streams.py", line 344, in read raise self._exception aiohttp.client_exceptions.ClientPayloadError: 400, message='Can not decode content-encoding: br'
> > > > new error :(
> > > 
> > > 
> > > https://github.com/MehulKhanna/PokeGrinder/releases/download/Full-Release/PokeGrinderExecutable.zip please try to use the executable given in this file
> > 
> > 
> > This version works fine, but when the captcha appears, there is an error | Time Elapsed: 0:00:02 | Encounters: 1 | Catches: 1 | Time Elapsed: 0:00:14 | Encounters: 2 | Catches: 2 Task exception was never retrieved future: <Task finished name='Task-25' coro=<timer() done, defined at C:\Users\ADMIN\Downloads\PokeGrinderExecutable\cogs\hunting.py:19> exception=TimeoutError()> Traceback (most recent call last): File "asyncio\tasks.py", line 456, in wait_for asyncio.exceptions.CancelledError
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last): File "C:\Users\ADMIN\Downloads\PokeGrinderExecutable\cogs\hunting.py", line 21, in timer await command() File "discord\commands.py", line 615, in **call** File "discord\commands.py", line 261, in **call** File "discord\commands.py", line 128, in **call** File "asyncio\tasks.py", line 458, in wait_for asyncio.exceptions.TimeoutError
> 
> Can you please check and see if this happens with every captcha you encounter?
yes, when the captcha appears, the activity stops and nothing happens after that

**Comment by MehulKhanna** [comment]
> > > > > > > C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\bot.py:618: RuntimeWarning: coroutine 'setup' was never awaited setup(self) RuntimeWarning: Enable tracemalloc to get the object allocation traceback Traceback (most recent call last): File "C:\Users\ADMIN\Downloads\PokeGrinder-master\PokeGrinder-master\main.py", line 18, in asyncio.run(load_cogs()) File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "C:\Users\ADMIN\Downloads\PokeGrinder-master\PokeGrinder-master\main.py", line 14, in load_cogs await client.load_extension("cogs.startup") TypeError: object NoneType can't be used in 'await' expression
> > > > > > 
> > > > > > 
> > > > > > This error has been fixed, please try to install using the executable that has now been provided and installation instructions for which are provided in the readme.
> > > > > 
> > > > > 
> > > > > Traceback (most recent call last): File "C:\Users\ADMIN\Downloads\PokeGrinder-master (1)\PokeGrinder-master\main.py", line 20, in client.run(client.token) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 742, in run asyncio.run(runner()) File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 739, in runner await self.start(*args, **kwargs) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 712, in start await self.login(token) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 583, in login data = await state.http.static_login(token.strip()) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\http.py", line 660, in static_login await self.startup() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\http.py", line 378, in startup self.user_agent, self.browser_version, self.client_build_number = ua, bv, bn = await utils._get_info(session) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\utils.py", line 1246, in _get_info bn = await _get_build_number(session) File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\discord\utils.py", line 1255, in _get_build_number login_page = await login_page_request.text() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\aiohttp\client_reqrep.py", line 1076, in text await self.read() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\aiohttp\client_reqrep.py", line 1032, in read self._body = await self.content.read() File "C:\Users\ADMIN\AppData\Roaming\Python\Python310\site-packages\aiohttp\streams.py", line 344, in read raise self._exception aiohttp.client_exceptions.ClientPayloadError: 400, message='Can not decode content-encoding: br'
> > > > > new error :(
> > > > 
> > > > 
> > > > https://github.com/MehulKhanna/PokeGrinder/releases/download/Full-Release/PokeGrinderExecutable.zip please try to use the executable given in this file
> > > 
> > > 
> > > This version works fine, but when the captcha appears, there is an error | Time Elapsed: 0:00:02 | Encounters: 1 | Catches: 1 | Time Elapsed: 0:00:14 | Encounters: 2 | Catches: 2 Task exception was never retrieved future: <Task finished name='Task-25' coro=<timer() done, defined at C:\Users\ADMIN\Downloads\PokeGrinderExecutable\cogs\hunting.py:19> exception=TimeoutError()> Traceback (most recent call last): File "asyncio\tasks.py", line 456, in wait_for asyncio.exceptions.CancelledError
> > > The above exception was the direct cause of the following exception:
> > > Traceback (most recent call last): File "C:\Users\ADMIN\Downloads\PokeGrinderExecutable\cogs\hunting.py", line 21, in timer await command() File "discord\commands.py", line 615, in **call** File "discord\commands.py", line 261, in **call** File "discord\commands.py", line 128, in **call** File "asyncio\tasks.py", line 458, in wait_for asyncio.exceptions.TimeoutError
> > 
> > 
> > Can you please check and see if this happens with every captcha you encounter?
> > yes, when the captcha appears, the activity stops and nothing happens after that

I know what could've caused this error but I am unable to reproduce this error myself. Did you make any changes to any files except config.json in the PokeGrinderExecutable folder? Can you please share the image of the captcha message?

**Comment by ducpro0211kk** [comment]
Is there a faster way to contact you? telegram or facebook?

**Comment by MehulKhanna** [comment]
> Is there a faster way to contact you? telegram or facebook?

https://t.me/PokeGrinder

**Comment by ducpro0211kk** [comment]
![image](https://user-images.githubusercontent.com/65226065/194053604-56099b39-2c04-4997-8836-798235c8850b.png)
i can't chat

**Comment by MehulKhanna** [comment]
> ![image](https://user-images.githubusercontent.com/65226065/194053604-56099b39-2c04-4997-8836-798235c8850b.png) i can't chat

Now you can
