### ISSUE TITLE
error while starting main.py

### ISSUE THREAD

**Issue by TestUser5643** [MehulKhanna/PokeGrinder#64]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/discord/http.py", line 1058, in static_login
    data = await self.get_me()
  File "/usr/local/lib/python3.10/dist-packages/discord/http.py", line 934, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/PokeGrinder/main.py", line 94, in <module>
    asyncio.run(start())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/content/PokeGrinder/main.py", line 91, in start
    await asyncio.gather(*[start_bots(token) for token in list(config.keys())[5:]])
  File "/content/PokeGrinder/main.py", line 87, in start_bots
    await bot.start(token=token)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 1025, in start
    await self.login(token)
  File "/usr/local/lib/python3.10/dist-packages/discord/client.py", line 867, in login
    data = await state.http.static_login(token.strip())
  File "/usr/local/lib/python3.10/dist-packages/discord/http.py", line 1062, in static_login
    raise LoginFailure('Improper token has been passed') from exc
discord.errors.LoginFailure: Improper token has been passed

it was working the other day and now i try running it and it tells me this

**Comment by lufy20106** [comment]
Your token is dead
Try new one
