### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by AnkiTMohanT** [MehulKhanna/PokeGrinder#75]
I got this problem i successfully managed to installed tensorflow ultralytics pillow on termux
![Screenshot_2024-09-01-13-09-47-898_com termux](https://github.com/user-attachments/assets/4bdd6e54-716d-4903-ae3c-c88bb0b08b55)

**Comment by MehulKhanna** [comment]
> I got this problem i successfully managed to installed tensorflow ultralytics pillow on termux
> 
> Traceback (most recent call last): File "/root/PokeGrinder/main.py", line 11, in from cogs.captcha import Captcha File "/root/PokeGrinder/cogs/captcha.py", line 7, in from modules.captcha_solver import solve_captcha File "/root/PokeGrinder/modules/captcha_solver.py", line 4, in from ultralytics import YOLO File "/root/venv/lib/python3.12/site-packages/ultralytics/**init**.py", line 5, in from ultralytics.data.explorer.explorer import Explorer File "/root/venv/lib/python3.12/site-packages/ultralytics/data/**init**.py", line 3, in from .base import BaseDataset File "/root/venv/lib/python3.12/site-packages/ultralytics/data/base.py", line 12, in import cv2 File "/root/venv/lib/python3.12/site-packages/cv2/**init**.py", line 181, in bootstrap() File "/root/venv/lib/python3.12/site-packages/cv2/**init**.py", line 153, in bootstrap native_module = importlib.import_module("cv2") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/importlib/**init**.py", line 90, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ImportError: libGL.so.1: cannot open shared object file: No such file or directory

Install libgl and then try.
